<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>FluentDesigner</RootNamespace>
    <Platforms>x86;x64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>enable</Nullable>
	<DebugType>full</DebugType>
	<DebugSymbols>true</DebugSymbols>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	<ApplicationManifest>app.manifest</ApplicationManifest>
	<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
	  <WindowsPackageType>None</WindowsPackageType>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Shaders\GridShader.hlsl" />
    <EmbeddedResource Include="Shaders\OutlineShader.hlsl" />
    <EmbeddedResource Include="Shaders\Shader.hlsl" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
    <Content Include="StoreLogo.ico" />
	<Content Include="Assets\Icons\Light\*.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Textures\*.png" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Microsoft.Graphics.Win2D" Version="1.3.2" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.7463" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.251106002" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="R3" Version="1.3.0" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
    <PackageReference Include="UniTask" Version="2.5.10" />
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.2" />
    <PackageReference Include="Vortice.Direct3D12" Version="3.8.2" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.2" />
    <PackageReference Include="Vortice.WinUI" Version="3.8.2" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\RailIndexCurvePanel.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\MultiSelectPanel.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\TimeRulerPanel.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\TimeRulerTrack.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\TrackPreviewTrack.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\CsvMarkerTrack.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\WaveformTrack.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\TimelineControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\PlaybackPanel.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\VelocityCurveComponent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\DescriptionComponent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\TimingComponent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\MeshRendererComponent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\TransformComponent.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\InspectorView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\HierarchyView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Control\ViewportD3D12.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <!-- Publish Properties -->
  <PropertyGroup>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <IncludeSymbols>False</IncludeSymbols>
    <EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
    <PublishTrimmed>false</PublishTrimmed>
    <ApplicationIcon>StoreLogo.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <WarningLevel>1</WarningLevel>
    <Optimize>False</Optimize>
    <DebugType>portable</DebugType>
	  <SelfContained>true</SelfContained>
	  <PublishSingleFile>true</PublishSingleFile>
	  <PublishTrimmed>false</PublishTrimmed>
	  <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <WarningLevel>1</WarningLevel>
    <Optimize>False</Optimize>
    <DebugType>portable</DebugType>
	  <SelfContained>true</SelfContained>
	  <PublishSingleFile>true</PublishSingleFile>
	  <PublishTrimmed>false</PublishTrimmed>
	  <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <WarningLevel>1</WarningLevel>
    <Optimize>False</Optimize>
    <DebugType>portable</DebugType>
	  <SelfContained>true</SelfContained>
	  <PublishSingleFile>true</PublishSingleFile>
	  <PublishTrimmed>false</PublishTrimmed>
	  <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <WarningLevel>1</WarningLevel>
    <Optimize>False</Optimize>
    <DebugType>portable</DebugType>
	  <SelfContained>false</SelfContained>
	  <PublishSingleFile>true</PublishSingleFile>
	  <PublishTrimmed>false</PublishTrimmed>
	  <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>
</Project>